image: alpine:3.17

stages:
  - test
  - sonarCheck

# MySQL database (required for backend unit tests)
services:
  - mysql
variables:
  MYSQL_DATABASE: swe
  MYSQL_USER: swe
  MYSQL_PASSWORD: password
  MYSQL_RANDOM_ROOT_PASSWORD: 'true'

# Add dependencies for Java and React
.before_script_template:
  before_script:
    - apk add --update maven yarn npm nodejs

backend-unit-test-job:
  extends: .before_script_template
  stage: test
  script:
    - echo "Running Spring Boot unit tests..."
    - mvn -Dskip.npm -Dskip.yarn -Dskip.installnodenpm -Dskip.installyarn test -Dspring.datasource.url="jdbc:mysql://mysql:3306/swe"
  allow_failure: false
  retry: 1

frontend-unit-test-job:
  extends: .before_script_template
  stage: test
  script:
    - echo "Running React unit tests..."
    - cd frontend
    - yarn
    - yarn test
  allow_failure: false
  retry: 1

arduino-build-job:
  stage: test
  script:
    - apk add --update python3 gcompat git
    - python3 -m ensurepip
    - pip3 install platformio
    - echo "Checking if Arduino code builds..."
    - cd arduino
    - pio run
  allow_failure: false
  retry: 1

sonarqube-check:
  extends: .before_script_template
  stage: sonarCheck
  variables:
    SONAR_USER_HOME: '${CI_PROJECT_DIR}/code/.sonar'
    GIT_DEPTH: '0'
  cache:
    key: '${CI_JOB_NAME}'
    paths:
      - .sonar/cache
  script:
    - echo "Running sonar analysis for ${SONAR_PROJECT_KEY}"
    - mvn -Dsonar.projectKey=${SONAR_PROJECT_KEY} -Dsonar.projectName="${CI_PROJECT_NAME}" --fail-at-end verify sonar:sonar
  allow_failure: true
  retry: 1
  only:
    - main
    - dev
