version: '3'

services:

  mysql-development:
    image: mysql:8.0.17
    environment:
      MYSQL_ROOT_PASSWORD: helloworld
      MYSQL_DATABASE: testapp
    ports:
      - "8080:3306"
#see https://betterprogramming.pub/setting-up-mysql-database-in-a-docker-d6c69a3e9afe