
-- $2y$10$P7im4OMw6hsnPWLpJ1nVKup1jlEFsLIek9D3lglmZv.Tq05GDEhMS -> passwd
INSERT INTO USERX (FIRST_NAME, LAST_NAME, PASSWORD, USERNAME, CREATE_DATE, EMAIL) VALUES('Admin', 'Istrator', 'passwd', 'admin', '2016-01-01 00:00:00', 'admin@example.at')
INSERT INTO USERX_USER_ROLE (USERX_USERNAME, ROLES) VALUES ('admin', 'ADMIN')
INSERT INTO USERX_USER_ROLE (USERX_USERNAME, ROLES) VALUES ('admin', 'USER')
INSERT INTO USERX (FIRST_NAME, LAST_NAME, PASSWORD, USERNAME, CREATE_DATE, EMAIL) VALUES('Susi', 'Gruen', 'passwd', 'susi', '2016-01-01 00:00:00', 'susi@example.at')
INSERT INTO USERX_USER_ROLE (USERX_USERNAME, ROLES) VALUES ('susi', 'GARDENER')
INSERT INTO USERX_USER_ROLE (USERX_USERNAME, ROLES) VALUES ('susi', 'USER')
INSERT INTO USERX (FIRST_NAME, LAST_NAME, PASSWORD, USERNAME, CREATE_DATE, EMAIL) VALUES('Max', 'Mustermann', 'passwd', 'max', '2016-01-01 00:00:00', 'max@example.at')
INSERT INTO USERX_USER_ROLE (USERX_USERNAME, ROLES) VALUES ('max', 'USER')
INSERT INTO USERX (FIRST_NAME, LAST_NAME, PASSWORD, USERNAME, CREATE_DATE, EMAIL) VALUES('Elvis', 'The King', 'passwd', 'elvis', '2016-01-01 00:00:00', 'elvis@example.at')
INSERT INTO USERX_USER_ROLE (USERX_USERNAME, ROLES) VALUES ('elvis', 'ADMIN')
INSERT INTO USERX_USER_ROLE (USERX_USERNAME, ROLES) VALUES ('elvis', 'USER')