INSERT INTO USERX (FIRST_NAME, LAST_NAME, PASSWORD, USERNAME, CREATE_DATE, EMAIL, USER_ROLE) VALUES('Admin', 'Istrator', 'passwd', 'admin', '2016-01-01 00:00:00', 'admin@example.at', 'ADMIN')
INSERT INTO USERX (FIRST_NAME, LAST_NAME, PASSWORD, USERNAME, CREATE_DATE, EMAIL, USER_ROLE) VALUES('Susi', 'Gruen', 'passwd', 'susi', '2016-01-01 00:00:00', 'susi@example.at', 'GARDENER')
INSERT INTO USERX (FIRST_NAME, LAST_NAME, PASSWORD, USERNAME, CREATE_DATE, EMAIL, USER_ROLE) VALUES('Max', 'Mustermann', 'passwd', 'max', '2016-01-01 00:00:00', 'max@example.at', 'USER')
INSERT INTO USERX (FIRST_NAME, LAST_NAME, PASSWORD, USERNAME, CREATE_DATE, EMAIL, USER_ROLE) VALUES('Elvis', 'The King', 'passwd', 'elvis', '2016-01-01 00:00:00', 'elvis@example.at', 'ADMIN')
INSERT INTO USERX (FIRST_NAME, LAST_NAME, PASSWORD, USERNAME, CREATE_DATE, EMAIL, USER_ROLE) VALUES('Hans', 'G', 'passwd', 'hans', '2016-01-01 00:00:00', 'hans@example.at', 'GARDENER')
INSERT INTO USERX (FIRST_NAME, LAST_NAME, PASSWORD, USERNAME, CREATE_DATE, EMAIL, USER_ROLE) VALUES('Peter', 'G', 'passwd', 'peter', '2016-01-01 00:00:00', 'peter@example.at', 'GARDENER')
INSERT INTO USERX (FIRST_NAME, LAST_NAME, PASSWORD, USERNAME, CREATE_DATE, EMAIL, USER_ROLE) VALUES('Franz', 'g', 'passwd', 'franz', '2016-01-01 00:00:00', 'franz@example.at', 'GARDENER')

INSERT INTO ACCESS_POINT (ACTIVE, LAST_UPDATE, AP_NAME, SERVER_ADDRESS) VALUES ('true', '2016-01-01 00:00:00', 'AP 1', CAST( 16843009 AS BINARY(4) )) -- 16843009 is in hexa 01010101 which is ip 1.1.1.1

INSERT INTO SENSOR_VALUES (VALUES_ID, AIR_PRESSURE, AIR_QUALITY, HUMIDITY, LIGHT_INTENSITY, SOIL_MOISTURE, TEMPERATURE) VALUES ('1', '20', '20', '20', '20', '20', '20')
INSERT INTO SENSOR_VALUES (VALUES_ID, AIR_PRESSURE, AIR_QUALITY, HUMIDITY, LIGHT_INTENSITY, SOIL_MOISTURE, TEMPERATURE) VALUES ('2', '0', '0', '0', '0', '0', '0')
INSERT INTO SENSOR_VALUES (VALUES_ID, AIR_PRESSURE, AIR_QUALITY, HUMIDITY, LIGHT_INTENSITY, SOIL_MOISTURE, TEMPERATURE) VALUES ('3', '30', '30', '30', '30', '30', '30')

INSERT INTO SENSOR_STATION (SS_ID, STATUS, AGGREGATION_PERIOD, AP_NAME, UPPER_VALUES_ID, LOWER_VALUES_ID) VALUES ('1', 'OK', '30', 'AP 1', '1', '2')
INSERT INTO SENSOR_STATION (SS_ID, STATUS, AGGREGATION_PERIOD, AP_NAME, UPPER_VALUES_ID, LOWER_VALUES_ID) VALUES ('2', 'OK', '60', 'AP 1', '3', '2')

INSERT INTO GARDENER_SS (USERNAME, SS_ID) VALUES ('susi', '1')
INSERT INTO GARDENER_SS (USERNAME, SS_ID) VALUES ('hans', '1')
INSERT INTO GARDENER_SS (USERNAME, SS_ID) VALUES ('peter', '1')
INSERT INTO GARDENER_SS (USERNAME, SS_ID) VALUES ('franz', '2')