
-- $2y$10$P7im4OMw6hsnPWLpJ1nVKup1jlEFsLIek9D3lglmZv.Tq05GDEhMS -> passwd
INSERT INTO USERX (FIRST_NAME, LAST_NAME, PASSWORD, USERNAME, CREATE_DATE, EMAIL, CREATE_USER_USERNAME, USER_ROLE) VALUES('Admin', 'Istrator', 'passwd', 'admin', '2016-01-01 00:00:00', 'admin@example.at', 'admin', 'ADMIN')
INSERT INTO USERX (FIRST_NAME, LAST_NAME, PASSWORD, USERNAME, CREATE_DATE, EMAIL, CREATE_USER_USERNAME, USER_ROLE) VALUES('Susi', 'Gruen', 'passwd', 'susi', '2016-01-01 00:00:00', 'susi@example.at', 'admin', 'GARDENER')
INSERT INTO USERX (FIRST_NAME, LAST_NAME, PASSWORD, USERNAME, CREATE_DATE, EMAIL, CREATE_USER_USERNAME, USER_ROLE) VALUES('Max', 'Mustermann', 'passwd', 'max', '2016-01-01 00:00:00', 'max@example.at', 'admin', 'USER')
INSERT INTO USERX (FIRST_NAME, LAST_NAME, PASSWORD, USERNAME, CREATE_DATE, EMAIL, CREATE_USER_USERNAME, USER_ROLE) VALUES('Elvis', 'The King', 'passwd', 'elvis', '2016-01-01 00:00:00', 'elvis@example.at', 'admin', 'ADMIN')
